### ISSUE TITLE
视频类型文章不支持, 导出csv发生异常

### ISSUE THREAD

**Issue by teaim** [kingbase/wechat_history_export#1]
标签weui_media_box appmsg js_video video_msg

示例: COCOS公众号 2019年8月28日那篇文章

**Comment by teaim** [comment]
![image](https://user-images.githubusercontent.com/20551753/88363278-16495980-cdb2-11ea-848d-99133e02e78a.png)

**Comment by kingbase** [comment]
多谢提供！
代码已经更新， @FreeLoopC 更新下试试看。
