### ISSUE TITLE
为啥在mac下不可用呢

### ISSUE THREAD

**Issue by okxiaochen** [kingbase/wechat_history_export#2]

**Comment by kingbase** [comment]
因为 Mac 下的微信桌面版没有提供“使用系统默认浏览器打开网页”，只有开启这个选项才能成功加载历史文章。

**Comment by dem0ns** [comment]
此时又一只mac党路过

**Comment by kingbase** [comment]
若有兴趣可以看下现在的原理并分析如何在 Mac 上实现：
开启“使用系统默认浏览器打开网页”选项后，当打开公众号文章链接时，会在链接中加上pass_ticket和exportkey等多个参数，此时再去打开公众号历史文章链接就可以加载。如果打开的是公众号文章的短链或者缺少某几个参数，则打开历史文章链接会提示：请使用微信客户端打开。
限于精力，没有细究到底微信采用的是何种机制判断，若苦逼 Mac 党真有需要，可以找台 Windows 尝试对比下。
@okdanta @nic329

**Comment by dem0ns** [comment]
好的好的，感谢大佬 @kingbase
