### ISSUE TITLE
导出的Excel中文乱码

### ISSUE THREAD

**Issue by lovecn** [kingbase/wechat_history_export#3]
如图，我用的WPS 
![image](https://user-images.githubusercontent.com/6429263/89158699-0fd09400-d5a1-11ea-968f-f6054a132466.png)

**Comment by kingbase** [comment]
抱歉这是个已知问题，同样现象也会出现在 Office Excel 上。
原因在于 WPS / Excel 似乎默认无法识别 UTF-8 编码的 csv 文件，反而可以识别 GBK 编码的 csv。
不如试试手动把 csv 的编码由 UTF-8 修改为 GBK 编码，在 Notepad++ 上比较好操作。
