### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by uwhatsup** [kingbase/wechat_history_export#5]
已经设置chorm浏览器
微信也设置 使用系统默认浏览器打开网页
但是每次打开链接后，点击插件都提示

请先设置微信桌面程序为“使用系统默认浏览器打开网页”，然后使用微信桌面程序打开链接，方可生效。

**Comment by kingbase** [comment]
可以把此时的链接发出来看下么？
另外使用的微信版本是什么呢？

**Comment by uwhatsup** [comment]
链接我测试了好几篇都不行：
https://mp.weixin.qq.com/s/fKCDfgi7LPRbhgObZ3y8gw
https://mp.weixin.qq.com/s/Op50R4A023zLA8VP3TrVPw
https://mp.weixin.qq.com/s/l7bk-jz8GELmAgZfwk_4Xg

PC端的微信是 微信测试版3.2.1.42

**Comment by kingbase** [comment]
我使用的微信版本是 2.6.8.50，你那边方便改用低版本微信吗？如果只是为这个公众号，可以使用后面附的链接。

微信比较封闭，可能是他们在新版本把这个功能去掉了。

你这给的链接，不符合预期。期望的是出现下面这样的链接：

https://mp.weixin.qq.com/s?__biz=MzA4NTY2ODA3MQ==&mid=2247485133&idx=1&sn=b0eb489215f9d008be05d8d42b7c31b9&chksm=9fd53f45a8a2b653fc02658dc32e04f318c19087b9971bfaee45b1e27fa85d20ab39fdc36f1b&mpshare=1&scene=24&srcid=0307B2UgkGVHjijUHVbHHxJB&sharer_sharetime=1615121308518&sharer_shareid=581c111496045ada57e9602a8e1111af&key=31aa7af5e6166155311c57a89235f4389039b84ef5df3b12d3f4f77662fd03ca9136c7c034dbef808ff2e1a1bec367589dea3b1a085b9a79a0d4394c763f0ac9daa2403ad6fb340a06363aaab0540725d1927a2c9521e4cbff145a51928234acf3fad7ab47b9ff1ec080b01b773390a4ff086e867bdd542c8e4a50ec29752234&ascene=14&uin=MjEwNzc1MTM4MA%3D%3D&devicetype=Windows+10&version=62060833&lang=zh_CN&exportkey=AV%2Fut9QUS%2FxJykpZpuFFUNo%3D&pass_ticket=N6LJmsz7sSoqhCT2bq1U9upZdqK0J9gpc%2BVGJg1Nfk2QACgmV0h4gWUjQVspO%2FK4&wx_header=0

**Comment by uwhatsup** [comment]
换低版本微信登录比较麻烦，我试试

**Comment by zh2040** [comment]
实测2.9.5版本可以使用，更早前的版本可能被限制登录。

**Comment by uwhatsup** [comment]
嗯，低版本测试可以使用了，谢谢！
